### ISSUE TITLE
examples do not compile

### ISSUE THREAD

**Issue by Kalle3D** [fhessel/esp32_https_server#34] opened 2019-01-28 01:30 UTC
The examples do not compile (for example Self-Signed-Certificate.ino)
Arduino IDE 1.8.8, Linux Ubuntu 14.04 LTS
Following errors while compiling:

In file included from /home/www/Arduino/libraries/esp32_https_server-master/src/WebsocketNode.hpp:7:0,
                 from /home/www/Arduino/libraries/esp32_https_server-master/src/ResourceResolver.hpp:12,
                 from /home/www/Arduino/libraries/esp32_https_server-master/src/HTTPServer.hpp:21,
                 from /home/www/Arduino/libraries/esp32_https_server-master/src/HTTPSServer.hpp:15,
                 from /home/www/Arduino/libraries/esp32_https_server-master/examples/Self-Signed-Certificate/Self-Signed-Certificate.ino:26:
/home/www/Arduino/libraries/esp32_https_server-master/src/WebsocketHandler.hpp:70:65: error: macro "send" requires 4 arguments, but only 2 given
  void send(std::string data, uint8_t sendType = SEND_TYPE_BINARY);
                                                                 ^
/home/www/Arduino/libraries/esp32_https_server-master/src/WebsocketHandler.hpp:71:79: error: macro "send" requires 4 arguments, but only 3 given
  void send(uint8_t *data, uint16_t length, uint8_t sendType = SEND_TYPE_BINARY);

**Comment by fhessel** [comment] 2019-01-28 22:01
That seems to be a conflict between the declaration of the `send` function and some macro that has been defined either in the Arduino Core or in esp-idf, over which I have no control. When this happened earlier, I just `#undef`ined those macros. 

Until I get to find the conflict and fix that error, you could try adding
```c++
#undef send
```
at line 12 of WebsocketHandler.hpp and see if that's a temporary workaround for you.

And to be able to reproduce that error: Did you use the most recent version of the ESP32 Arduino Core (1.0.1, released on Jan. 11th)? As compiling works for me using a previous version and I didn't test the library against that core by now, that would be my first guess for the cause.

**Comment by Kalle3D** [comment] 2019-01-29 01:51
Yes it was ESP32 Arduino Core 1.0.1 .
I did not try the #undef.

I downgraded to 1.0.0 with the Arduino IDE Board Manager, then it compiles without errors.
Then i upgraded to 1.0.1 again, and now it also compiles without errors!
It must have been some inconsistency in (my) Arduino IDE ESP32 libs.
I can not repoduce the compiler errors anymore.

**Comment by fhessel** [comment] 2019-01-29 03:58
Good to know that it works now. I'll close the issue for now, if you face any other errors, feel free to open it again or just file another one.

I'll also have a look at the compatibility with the newest Arduino Core and check whether I can identify any other compatibility problems there.

**Closed by fhessel** 2019-01-29 03:58 UTC
Labels: bug
