### ISSUE TITLE
Stack size, Timeout problem and MDNS

### ISSUE THREAD

**Issue by maxdd** [fhessel/esp32_https_server#6] opened 2018-06-09 10:07 UTC
After all the stuff i've written in this issue (now deleted, mostly kernel panics) i've noticed that the stack size of your example leads to frequent crashes. I've currently set it to 4096+256 and everything feels ok

```
xTaskCreatePinnedToCore(serverTask, "https443", 4096+256, NULL, 1, NULL, ARDUINO_RUNNING_CORE);
```

You should really add it in the README as a potential fix for kernel panic issues.
I'm still seeing connection timeout though
```
HTTPSServer->debug: [   ] Draining response buffer
HTTPSServer->debug: [zZz] Connection timeout exceeded, closing connection. fid= 0x1004
HTTPSServer->debug: [<--] Connection has been closed. fid =  0x1004
```

Also how do you #undef so that the debug output is turned off?
I've seen this but i got compile error everywhere

> // Debug Code. Undefine it to disable debugging output

Also i'm trying to give the ESP32 an hostname so that i can browse it directly

```
if (!MDNS.begin("esp32")) {
        Serial.println("Error setting up MDNS responder!");
        while (1) {
            delay(1000);
        }
    }
```
The code above is right before the server.start() call (i've also tried after) but even if it "begins" succesfully it is not working even if the following does (i can see the services being announced)
```
MDNS.addService("_https", "_tcp", 443);
MDNS.addServiceTxt("_https", "_tcp", "domus", "ESP32");
```

**Comment by fhessel** [comment] 2018-06-10 16:28
> After all the stuff i've written in this issue (now deleted, mostly kernel panics) i've noticed that the stack size of your example leads to frequent crashes. I've currently set it to 4096+256 and everything feels ok
> You should really add it in the README as a potential fix for kernel panic issues.

As the README mentions, the whole project needs proper documentation, I did not have enough time for it by now, but I created issue #7 for that and I hope I will find some time.

However, the error message you mentioned in the post's first version says: `Debug exception reason: Stack canary watchpoint triggered (https443)`, and especially for this error, the example file already [mentions increasing the stack size as a solution](https://github.com/fhessel/esp32_https_server/blob/master/https_server.cpp#L208). Again, you're right, the project needs a better documentation anyway.

> I'm still seeing connection timeout though

The timeout message will occur if keep-alive is set and no request is seen by the client for a certain period (defaults to 20 seconds). Do you experience unexpected timeouts? You can configure [this constant](https://github.com/fhessel/esp32_https_server/blob/master/https/HTTPSServerConstants.hpp#L36) to change the timeout. It's planned to expose the parameters of that file via API too, at least for those that are not required at compile time (to reserve memory).

> Also how do you #undef so that the debug output is turned off?

Undef may be the wrong word, as the macro cannot be expanded if you do so. Redefining them is the way to go.  You can replace the definitions in `HTTPSServerConstants.hpp` with this:
```
#define HTTPS_DLOG(X)
#define HTTPS_DLOGHEX(X,Y)
```

> The code above is right before the server.start() call (i've also tried after) but even if it "begins" succesfully it is not working [...]

Do you think this relates to the HTTPS server? Are you able to resolve the hostname properly if you write a minimal sketch that only sets up mDNS? I do not have that much experience with the mDNS library.

**Comment by maxdd** [comment] 2018-06-10 17:34
Regarding the timeout it seems to happen when something like this occur

```
HTTPSServer->debug: [   ] Draining response buffer
HTTPSServer->debug: [-->] New connection. Socket fid is:  0x1003
HTTPSServer->debug: [ERR] SSL_accept failed. Aborting handshake.
Fail.
HTTPSServer->debug: [-->] New connection. Socket fid is:  0x1004
HTTPSServer->debug: [ERR] SSL_new failed. Aborting handshake.
Fail.
HTTPSServer->debug: [   ] There is data on the connection socket. fid= 0x1001
HTTPSServer->debug: [ERR] An SSL error occured, fid= 0x1001
HTTPSServer->debug: [zZz] Connection timeout exceeded, closing connection. fid= 0x1002
HTTPSServer->debug: [<--] Connection has been closed. fid =  0x1002
```

Basically what you see here is a succesfull connection of the browser followed immediately by some Handshake fail (i don't know what the browser is doing at this point, surely im not the one asking for more).

Regarding the mDNS i have another sketch that worked but apparently if i compile it now it doesn't, maybe something is broken on the ESPmDNS side.
I've tried this https://github.com/espressif/arduino-esp32/blob/master/libraries/ESPmDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino

**Comment by fhessel** [comment] 2018-06-11 09:48
You need to look at the different connections. In the default configuration, the server allows for up to four parallel connections to different clients (or, which may be more accurate in your case: parallel connections to the same client application).

The `fid` that is logged with most of the entries is the internal socket ID for the connection that the log entry belongs to. So in your log, we can see four parallel connection (attempts). `0x1003` and `0x1004` fail in different stages of the SSL handshake (memory limitations may be a problem here), but `0x1002` has been opened at least 20 seconds earlier and is closed now as it was not used in the mean time by its client. I cannot tell what exactly caused the error for `0x1001` though.

However, the timeout for a connection is intended behavior. It's a trade-off between improving performance by skipping handshakes and preserving resources (as many open tls connections will notably affect your memory usage).

> (i don't know what the browser is doing at this point, surely im not the one asking for more)

Real desktop web browsers tend to do a lot of performance optimization based on the assumption that they are talking to a powerful webserver that is able to handle lots of connections easily. So what usually happens when you open https://youresp would be to open two parallel connections, one to do `GET /` and one to do `GET /favicon.ico`.

In general, the server still needs some more stability for parallel handshakes, but I'm not quite sure what would be the best way to achieve it.

**Comment by maxdd** [comment] 2019-03-13 18:48
Just came in to ask if you can somehow access the esp32 through hostname rather than through IP.
I'm using the normal WIFI.hostname command but even if i add https://xxx.local/ or xxx.local:443 i can't resolve it.

**Comment by squonk11** [comment] 2019-03-13 18:59
I think for this you need to activate mdns service. See here: [https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/mdns.html?highlight=mdns](url)

**Comment by fhessel** [comment] 2019-03-13 19:02
It depends.

On iPhone and Mac, .local address resolution is usually done by mDNS, so for a `.local`-address, you need something like `MDNS.begin("xxx")`. To my knowledge, this won't work for Windows, Linux or Android out of the box. And that's something different than the hostname used for example with DHCP.

For access via real hostname, you need to set the hostname and configure a local domain. Many consumer routers combine DHCP and a local DNS server, so that devices which are registered via DHCP can be accessed using `<hostname>.<router's local domain>`. An example: AVM's FritzBoxes (quite popular in Germany, I don't know if that's the case in other countries) use "fritz.box" as local domain. So if you use "xxx" as hostname and request an DHCP IP address, your router will bind and resolve `xxx.fritz.box` to your ESP's IP address from then. As the router advertises its DNS server via DHCP, all devices in your network should then be able to access your ESP in all browsers. Even without an mDNS implementation in the browser or Avahi client installed.

**Comment by maxdd** [comment] 2019-03-13 19:12
i made it work using 

if (!MDNS.begin(HOSTNAME)) {
        debug_println("Error setting up MDNS responder!");
        while (1) {
            delay(1000);
        }
    }

the HOSTNAME was too long and with "underscores", i guess it didnt like it.
Anyway i can now access it without using *.local since the HOSTNAME doesnt contain it explicitly

**Comment by fhessel** [comment] 2019-03-13 19:18
The `.local` part is predefined for link-local connections in mDNS.

For the mDNS hostname, it's best to stick to the recommendations in 3.5 of [RFC1034](https://tools.ietf.org/html/rfc1034), which state that letters, numbers and hyphens are the smallest subset of allowed characters for each part of domain names.

**Comment by fhessel** [comment] 2019-04-02 06:07
To summarize this issue:
- **Stack Problem/Kernel Panic**: Has been solved by increasing the stack size for the server task (and [the example](https://github.com/fhessel/esp32_https_server/blob/master/examples/Async-Server/Async-Server.ino#L87) has been changed accordingly
- **Configuration of Logging**: Can be solved by changing the macro definition as shown above. The [develop branch](https://github.com/fhessel/esp32_https_server/commit/a9fffa0a07c64b3cdbe0bb34d0ed3a43b7ee5ff4) finally also supports configuration using build options
- **Timeout after 20s**: Intended behavior to save resources
- **mDNS**: You found a solution that works for you

If I didn't miss anything, there are no problems left (for now)? Then I'd close this issue for now. If you have any further questions, bugs, ... – feel free to open another.

**Closed** 2019-04-09 09:24 UTC
